### PR TITLE
feature/goreleaser :: Adds support for goreleaser

### PR DESCRIPTION
**Pull request by reneManqueros**
Add support for goreleaser

### CODE REVIEW

**Comment by flythenimbus** [comment]
@reneManqueros Thanks for the PR! 

How is this different (or better) from what's already setup here:

https://github.com/dugajean/goke/blob/dev/.github/workflows/release.yml

I'm not familiar with goreleaser, so I'm wondering what the benefits are.

**Comment by reneManqueros** [comment]
@dugajean 
Goreleaser has support for gitlab and others, and also has some other features like notifications that could make it handy.
If someone decides to fork outside of github, they can use goreleaser to manage their releases.

**Comment by flythenimbus** [comment]
Okay, I see. Could adjust the file I linked above to run the releaser action after tests? I'm not sure if goreleaser has an action somewhere that can be used.

**Comment by reneManqueros** [comment]
I added a step to run the tests

**Review by flythenimbus — APPROVED** [review]
👍

**Pull request merged**
