### PR TITLE
Environment variables per task

### LINKED ISSUE #9: Local (per task) environment variables
Task declarations should accept an `env` key as well, that essentially allows the user to set up environment variables for a specific task. This variable would override any global ones for this specific task.

### PR DESCRIPTION
**Pull request by samthom**
Added env key for tasks, added env parsing to parseTasks() and refactored the whole parsing and setting of env variables to a different method setEnvVariables().

fixes #9

### CODE REVIEW

**Comment by flythenimbus** [comment]
@samthom Your work might be out of date with some recent changes I made. Could you please check that out before I review? Thanks! 😄 

Also, if you could unit test this, that would be great.

**Comment by samthom** [comment]
@dugajean I have updated the code and added a simple unit test for the time being. Please check and let me know if any change is needed.  Also I would like to work on the tests after this.

**Comment by flythenimbus** [comment]
@samthom Can you please run the local git hooks that I have provided with the repo? I have put instructions on how to install them here:

https://github.com/dugajean/goke#contributing

There are formatting issues in your code, which are preventing me from merging it in.

**Comment by samthom** [comment]
Screenshot 2022-10-08 at 9 19 05 AM

I ran it and made a commit so the pre hook can trigger.

**Comment by flythenimbus** [comment]
@samthom I ran your code through `gofmt` locally and it didn't pass - so I realized there were errors on my pre-commit and ci scripts. The main culprit is the mix of tabs and spaces.

Could you potentially run `gofmt` manually on your code? The new changes to the pre-commit hook should now catch problems though.

Apologies for the hassle. 😞

**Comment by samthom** [comment]
No problem I have updated the formatting. This should do it.

**Review by flythenimbus — APPROVED** [review]
Sweet! Thanks for your contribution 😄

**Pull request merged**
